---
title: "FPTdemo"
author: "Grant Poulsen"
date: "11/29/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

Purpose: Demonstrate the concept of first passage time

Run Time: Seconds

```{r library, message = F}

###Setup###
library(sde)
library(ggplot2)
library(R.matlab)
```


```{r}

### Make a few simulations and find their first passage times ###

#Parameters
r <- .05
K <- 2
a <- .023
h <- .38
q <- 5
phiVal <- .02

#Diffusion & Drift Vector
mu <- expression(r*x*(1-(x/K)) - (a*x^5)/(x^5 + h^5))
dif <- expression(phiVal*x)

#Data
fptDem <- vector(length = 3)

#Simulations
X <- sde.sim(t0 = 0,T = 4500,X0 = .3,N = 4500, M =3, drift = mu, sigma = dif, sigma.x = phiVal)

#Search through each simulation
for(j in 1:3){
   
   #Search through every recorded data point
   for(i in 1:4500){
      
      #Record & Break if barrier is surpassed (.9878)
      if(X[i,j] > .9798){
         
         fptDem[j] = i
         break
      }
   }
}

```


```{r}

#Plotting

t <- seq(from = 0, to = 4500, by =1)

#Plot ts1
plot(t,X[,1], type = 's', ylab = 'Population Density', xlab = 'Time', lwd = 2, cex.axis = 1.48, cex.lab = 1.48)

#Plot ts2
par(new = TRUE)
plot(t,X[,2], type = 's', ylab = '', xlab = '', axes = FALSE, lwd = 2)

#Plot ts3
par(new = TRUE)
plot(t,X[,3], type = 's', ylab = '', xlab = '', axes = FALSE, lwd = 2)

#Plot FPTs
points(x = fptDem[1], y = .9798, col = 'red', pch = 4,cex = 3, lwd = 2)
points(x = fptDem[2], y = .9798, col = 'red', pch = 4,cex = 3, lwd = 2)
points(x = fptDem[3], y = .9798, col = 'red', pch = 4,cex = 3, lwd = 2)

#Plot barrier
abline(a = NULL, b = NULL, h = .9798, v = NULL, lwd = 2, lty = 2, col = "blue")
```

